ci: update to kilted

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -12,24 +12,46 @@ on:
           - generate_parameter_library_py
           - parameter_traits
 
+      build_kilted:
+        type: boolean
+        default: true
+        description: "Release for Kilted"
+
+      build_jazzy:
+        type: boolean
+        default: true
+        description: "Release for Jazzy"
+
 jobs:
+  setup:
+    runs-on: ubuntu-latest
+    outputs:
+      distros: ${{ steps.set-distros.outputs.distros }}
+    steps:
+      - id: set-distros
+        run: |
+          distros=()
+          [ "${{ github.event.inputs.build_jazzy }}" == "true" ] && distros+=("jazzy")
+          [ "${{ github.event.inputs.build_kilted }}" == "true" ] && distros+=("kilted")
+
+          if [ ${#distros[@]} -eq 0 ]; then
+            echo "::error::No distros selected. Please enable release for at least one of the available distros."
+            exit 1
+          fi
+
+          echo "distros=$(jq -cn '$ARGS.positional' --args "${distros[@]}")" >> $GITHUB_OUTPUT
+
   build:
+    needs: setup
     strategy:
       fail-fast: true
       matrix:
+        ros_distro: ${{ fromJson(needs.setup.outputs.distros) }}
         job:
-          - runner: buildjet-2vcpu-ubuntu-2204
+          - runner: 2vcpu-ubuntu-2404
             arch: amd64
-            ros_distro: jazzy
-          - runner: buildjet-2vcpu-ubuntu-2204-arm
+          - runner: 2vcpu-ubuntu-2404-arm
             arch: arm64
-            ros_distro: jazzy
-          - runner: buildjet-2vcpu-ubuntu-2204
-            arch: amd64
-            ros_distro: iron
-          - runner: buildjet-2vcpu-ubuntu-2204-arm
-            arch: arm64
-            ros_distro: iron
 
     name: Build - ${{ matrix.job.arch }} - ${{ matrix.job.ros_distro }}
     runs-on: ${{ matrix.job.runner }}
@@ -54,7 +76,7 @@ jobs:
 
   release:
     name: Create Release
-    runs-on: buildjet-2vcpu-ubuntu-2204
+    runs-on: 2vcpu-ubuntu-2404
     needs:
       - build
 
